FROM quay.io/nyulibraries/primo-explore-devenv:latest

ARG CENTRAL_PACKAGE_RELEASE

ENV DEVENV_PATH /app/
ENV CUSTOM_PACKAGE_PATH /app/primo-explore/custom/
ENV CUSTOM_VIEW_PATH ${CUSTOM_PACKAGE_PATH}/NYU

WORKDIR ${CUSTOM_VIEW_PATH}

ADD . .

WORKDIR ${CUSTOM_PACKAGE_PATH}

ADD ${CENTRAL_PACKAGE_RELEASE} .
RUN unzip CENTRAL_PACKAGE.zip && rm CENTRAL_PACKAGE.zip

WORKDIR ${DEVENV_PATH}

EXPOSE 8004 3001

CMD yarn start --host=0.0.0.0